import Head from 'next/head'
import Layout from "@/components/Layout";
import Image from 'next/image'
import profileImage from '../../public/images/profile/developer-pic-3.png'
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import {LinkArrow} from "@/components/Icons";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />

      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className='pt-0'>
            <div className="flex items-center justify-between w-full">

                <div className='w-1/2'>
                    <Image src={profileImage} alt="ProfileImage" className='h-auto w-4/5' />
                </div>

                <div className='w-1/2 flex flex-col items-left self-center'>

                    <AnimatedText
                        text='Home Page Heading - If I Make This Bigger' className='!text-6xl !text-left'/>
                    <p
                        className='my-4 text-base font-medium'>
                        A little description about you</p>

                    <div className='flex items-center self-start mt-2'>

                        <Link
                            href='/dummy.pdf'
                            target={"_blank"}
                            className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark'
                        >
                            Resume <LinkArrow className={"w-6 ml-1"}/>

                        </Link>

                        <Link
                            href='mailto:irishm.1102@gmail.com'
                            target={"_blank"}
                            className='ml-4 text-lg font-medium capitalize text-dark underline'
                        >
                            Contact</Link>
                    </div>

                </div>
            </div>

        </Layout>
      </main>
    </>
  )
}
